name: Linter
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - name: Install dependencies
        run: npm ci
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.7
        with:
          path: "."
          files: |
            **/*.js
          diff_relative: true
      - name: Lint
        run: |
          FILES=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
            if [[ $file == *.js ]]; then
              FILES="${{ format('$FILES {0}', '$file') }}"
            fi
          done
          npm run lint $FILES